services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    volumes:
      - .:/app:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
